global:
  environment: development
  tls:
    enabled: false

services:
  gateway:
    replicas: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      keda:
        enabled: false
  query-service:
    replicas: 1
    env:
      RUST_LOG: info
      DISTRIBUTED_QUERY_WORKERS: "2"
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      keda:
        enabled: false
  pipeline-service:
    replicas: 1
    env:
      RUST_LOG: info
      DISTRIBUTED_PIPELINE_WORKERS: "2"
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      keda:
        enabled: false
  geospatial-service:
    replicas: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
